name: Notify Discord on Version Change

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read version
        id: version
        run: |
          VERSION=$(cat version.txt)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Get Release Info
        id: release
        run: |
          RESPONSE=$(curl -s \
            https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ steps.version.outputs.version }})

          BODY=$(echo "$RESPONSE" | jq -r '.body')
          URL=$(echo "$RESPONSE" | jq -r '.html_url')
          NAME=$(echo "$RESPONSE" | jq -r '.name')

          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "url=$URL" >> $GITHUB_OUTPUT
          echo "name=$NAME" >> $GITHUB_OUTPUT

      - name: Send Discord Webhook
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "$(jq -n \
            --arg version "${{ steps.version.outputs.version }}" \
            --arg body "${{ steps.release.outputs.body }}" \
            --arg url "${{ steps.release.outputs.url }}" \
            '{
              content:
              ("🚀 Nouvelle version : **" + $version + "**\n\n"
              + $body + "\n\n"
              + $url)
            }')" \
          ${{ secrets.DISCORD_WEBHOOK }}
